const mongoose=require('mongoose');
const S=mongoose.Schema;
const O=S.Types.ObjectId;
const mk=(n,d)=>mongoose.model(n,new S(d,{timestamps:true}));
module.exports={
  Material:mk('Material',{title:{type:String,required:true},description:{type:String,default:''},subject_id:{type:Number,required:true},type:{type:String,default:'pdf'},file_url:{type:String,default:''},cloudinary_id:{type:String,default:''},size:{type:String,default:''},premium:{type:Boolean,default:true},tutor_id:{type:O,ref:'User'},downloads:{type:Number,default:0}}),
  Assignment:mk('Assignment',{title:{type:String,required:true},description:{type:String,default:''},subject_id:{type:Number,required:true},due_date:{type:String,default:''},tutor_id:{type:O,ref:'User'},file_url:{type:String,default:''},max_marks:{type:Number,default:100}}),
  Submission:mk('Submission',{assignment_id:{type:O,ref:'Assignment',required:true},student_id:{type:O,ref:'User',required:true},content:{type:String,default:''},file_url:{type:String,default:''},grade:{type:String,default:''},feedback:{type:String,default:''},status:{type:String,enum:['submitted','graded'],default:'submitted'},marks:{type:Number,default:null}}),
  Test:mk('Test',{title:{type:String,required:true},subject_id:{type:Number,required:true},duration:{type:Number,default:30},tutor_id:{type:O,ref:'User'}}),
  Question:mk('Question',{test_id:{type:O,ref:'Test',required:true},type:{type:String,enum:['mcq','truefalse','short'],default:'mcq'},question:{type:String,required:true},options:[{type:String}],answer:{type:String,required:true},order_num:{type:Number,default:0}}),
  TestResult:mk('TestResult',{test_id:{type:O,ref:'Test',required:true},student_id:{type:O,ref:'User',required:true},answers:{type:S.Types.Mixed,default:{}},score:{type:Number,default:0},total:{type:Number,default:0},percent:{type:Number,default:0},taken_at:{type:Date,default:Date.now}}),
  ResultComment:mk('ResultComment',{result_id:{type:O,ref:'TestResult',required:true},tutor_id:{type:O,ref:'User',required:true},comment:{type:String,required:true},question_index:{type:Number,default:-1}}),
  Message:mk('Message',{sender_id:{type:O,ref:'User',required:true},receiver_id:{type:O,ref:'User',required:true},content:{type:String,default:''},image_url:{type:String,default:''},read:{type:Boolean,default:false}}),
  GroupMessage:mk('GroupMessage',{subject_id:{type:Number,required:true},sender_id:{type:O,ref:'User',required:true},content:{type:String,default:''},image_url:{type:String,default:''}}),
  LiveClass:mk('LiveClass',{title:{type:String,required:true},subject_id:{type:Number,required:true},tutor_id:{type:O,ref:'User'},meet_link:{type:String,default:''},scheduled_date:{type:String,default:''},scheduled_time:{type:String,default:''},status:{type:String,enum:['upcoming','live','ended'],default:'upcoming'},description:{type:String,default:''},recording_url:{type:String,default:''}}),
  Subscription:mk('Subscription',{student_id:{type:O,ref:'User',required:true},subject_id:{type:Number,required:true},payment_status:{type:String,enum:['pending','approved','rejected'],default:'pending'},status:{type:String,enum:['active','expired','inactive'],default:'inactive'},amount:{type:Number,default:85},expires_at:{type:Date},months:{type:Number,default:1}}),
  PaymentRequest:mk('PaymentRequest',{student_id:{type:O,ref:'User',required:true},subject_id:{type:Number,required:true},amount:{type:Number,default:85},months:{type:Number,default:1},method:{type:String,default:'mtn'},transaction_id:{type:String,default:''},receipt_url:{type:String,default:''},cloudinary_id:{type:String,default:''},status:{type:String,enum:['pending','approved','rejected'],default:'pending'},notes:{type:String,default:''},admin_note:{type:String,default:''}}),
  Announcement:mk('Announcement',{title:{type:String,required:true},content:{type:String,required:true},important:{type:Boolean,default:false},admin_id:{type:O,ref:'User'}}),
};
